title: Migrating MS Access applications to Java
description: And how CUBA platform helps to do this
theme: jekyll-theme-cayman
show_downloads: true
locale: en-US
words_per_minute: 200
repository: dyakonoff/access-to-cuba-migration-samples
